apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linode-block-storage-encrypted
  namespace: kube-system
parameters:
  linodebs.csi.linode.com/encrypted: "true"
allowVolumeExpansion: true
provisioner: linodebs.csi.linode.com
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linode-block-storage-retain-encrypted
  namespace: kube-system
parameters:
  linodebs.csi.linode.com/encrypted: "true"
allowVolumeExpansion: true
provisioner: linodebs.csi.linode.com
reclaimPolicy: Retain