apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  method: plugin
  cluster:
    name: cluster-kubecon-london
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
