apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: paris-object
spec:
  configuration:
    destinationPath: "s3://paris-bucket/"
    endpointURL: "https://fr-par-1.linodeobjects.com"
    s3Credentials:
      accessKeyId:
        name: backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: backup-creds
        key: ACCESS_SECRET_KEY
      region:
        name: backup-creds
        key: REGION
    wal:
      compression: "bzip2"
